=== AdaDesi/corsoCodifica/Materials/XSLT-9780596527211-master/XSLT-2E-examples/AppendixA/po.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- po.xsd -->
<xs:schema 
  xmlns="http://www.oreilly.com/xslt"
  targetNamespace="http://www.oreilly.com/xslt"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="purchase-order">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="date" 
          minOccurs="1" maxOccurs="1"/>
        <xs:element ref="customer"
        minOccurs="1" maxOccurs="1"/>
        <xs:element ref="items"
          minOccurs="1" maxOccurs="1"/> 
      </xs:sequence>
      <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="date">
    <xs:complexType>
      <xs:attribute name="year" type="xs:integer"/>
      <xs:attribute name="month" type="xs:integer"/>
      <xs:attribute name="day" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="customer">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="address" minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:integer"/>
      <xs:attribute name="level" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="address">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name"
          minOccurs="1" maxOccurs="1"/>
        <xs:element ref="street"
          minOccurs="1" maxOccurs="1"/>
        <xs:element ref="city"
          minOccurs="1" maxOccurs="1"/>
        <xs:element ref="state"
          minOccurs="1" maxOccurs="1"/>
        <xs:element ref="zip"
          minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="type" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="name">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="title"
          minOccurs="0" maxOccurs="1"/>
        <xs:element ref="first-name"
          minOccurs="1" maxOccurs="1"/>
        <xs:element ref="last-name"
          minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="title" type="xs:string"/>
  <xs:element name="first-name" type="xs:string"/>
  <xs:element name="last-name" type="xs:string"/>

  <xs:element name="street" type="xs:string"/>
  <xs:element name="city" type="xs:string"/>
  <xs:element name="state" type="xs:string"/>
  <xs:element name="zip" type="xs:string"/>
  
  <xs:element name="items">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item" minOccurs="1" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="partname"
          minOccurs="1" maxOccurs="1"/>
        <xs:element ref="qty"
          minOccurs="1" maxOccurs="1"/>
        <xs:element ref="price"
          minOccurs="1" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="part-no" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="partname" type="xs:string"/>
  <xs:element name="qty" type="xs:integer"/>
  <xs:element name="price" type="xs:float"/>

</xs:schema>

=== AdaDesi/corsoCodifica/Materials/XSLT-9780596527211-master/XSLT-2E-examples/AppendixD/po-schema-ns.xml
<?xml version="1.0"?>
<!-- po-schema-ns.xml -->
<purchase-order id="38292" 
  xmlns="http://www.oreilly.com/xslt"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.oreilly.com/xslt 
                      po.xsd">
  <date year="2001" month="6" day="19"/>
  <customer id="4738" level="Platinum">
    <address type="business">
      <name>
        <title>Mr.</title>
        <first-name>Chester Hasbrouck</first-name>
        <last-name>Frisby</last-name>
      </name>
      <street>1234 Main Street</street>
      <city>Sheboygan</city>
      <state>WI</state>
      <zip>48392</zip>
    </address>
  </customer>
  <items>
    <item part-no="28392-33-TT">
      <partname>Turnip Twaddler</partname>
      <qty>3</qty>
      <price>9.95</price>
    </item>
    <item part-no="28100-38-CT">
      <partname>Clam Teaser</partname>
      <qty>7</qty>
      <price>39.95</price>
    </item>
  </items>
</purchase-order>
